#!/bin/sh

uncluttler -idle 0 &
xset s off -dpms 2> /dev/null &
xset r rate 240 40 &
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape' &
xrdb ~/.config/X11/Xresources &
dwmblocks &
picom --no-fading-openclose &
sxhkd &
dunst &

if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent -t 1h > "$XDG_RUNTIME_DIR/ssh-agent.env"
fi
if [[ ! "$SSH_AUTH_SOCK" ]]; then
    source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
fi

while true; do 
	dbus-launch dwm 2> /dev/null 
done
