#!/bin/sh

xset s off -dpms 2> /dev/null &
xset r rate 350 40 &
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape' &
xrdb ~/.config/X11/Xresources &
feh --no-fehbg --bg-fill ~/Pictures/wallpapers/joker-wallpaper.png &
dwmblocks &
picom --no-fading-openclose &
sxhkd &
dunst &

while true; do
	dbus-launch dwm 2> /dev/null
done
