#!/bin/sh

xsettingsd &
xset s off -dpms 2> /dev/null &
xset r rate 350 40 &
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape' &
numlockx &
xrdb ~/.config/X11/Xresources &
hsetroot -solid "#4c566a"
picom &
sxhkd &
dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

while true; do
	exec i3
done
