#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus

yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off

yabai -m config window_shadow                off
yabai -m config window_opacity_duration      0.0
yabai -m config window_opacity               off

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# mouse support
yabai -m config mouse_modifier               cmd
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

# app exclusions
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add app='^System Settings$' manage=off
yabai -m rule --add title='Information$' manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add app='^Steam$' manage=off
yabai -m rule --add app='^UTM$' manage=off

# disable animations when opening and closing windows
defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false

# accelerated playback when adjusting the window size
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

echo "yabai configuration loaded.."
