import = [
  "~/.config/alacritty/one_dark.toml",
  "~/.config/alacritty/keybindings.toml",
]
live_config_reload = true

[window]
dynamic_padding = true

[font]
size = 12.0

[font.bold]
family = "Terminus"
style = "Bold"

[font.bold_italic]
family = "Terminess Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Terminess Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Terminus"
style = "Regular"
